### ISSUE TITLE
Windows Defender trojan alert in Transformers2_Launcher.exe - Win32/AgentTesla!ml

### ISSUE THREAD

**Issue by techhitnz** [argonlefou/TSR_Loader#2]
False positive?

![image](https://github.com/argonlefou/TSR_Loader/assets/32992068/f54a3096-6f21-4ab8-9869-8e8d2e4597bd)

**Comment by argonlefou** [comment]
I suppose it is.
I enabled Windows Defender to check the file right after beeing compiled and it gets the same results.
I ran the file on [virus total](https://www.virustotal.com/gui/file/6bbdc910419fe4c2ccca4e31c4a1ebbccf9e21848b40ca714d489ff10797aa2c/detection) and as usual, some see virus, some don't.

I also had this issue a couple of time with [DemulShooter](https://github.com/argonlefou/DemulShooter/issues/213) and it disappeared after some code change and a new version

I guess the code signature may match some virus signature, especially as I'm manipulating memory of other process with these tools

That's why I'm publishing the code here on github, so that you can check (or make check) that everything is OK and compile it yourself (I can't rule out a corrupted Visual Studio on my side, integrating trojan at compile time but it's ....well not something I ever heard about)
